### ISSUE TITLE
When using the metropolis theme, beamerswitch messes up standout frame

### ISSUE THREAD

**Issue by jlconlin** [alex-ball/beamerswitch#16]
I like using the nice [metropolis theme](https://github.com/matze/mtheme) because it looks really nice. One of the features I like is the `standout` frame.

However, beamerswitch somehow breaks things. All slides after the standout frame, are also standout frames. This should not be. 

I've developed a MWE showing the difference when using just plain beamer, and another where all I change is switching from using beamer to beamerswitch.

[beamer.pdf](https://github.com/alex-ball/beamerswitch/files/5719688/beamer.pdf)

[beamerswitch.pdf](https://github.com/alex-ball/beamerswitch/files/5719687/beamerswitch.pdf)

```latex
\documentclass{beamerswitch}
% \docuemntclass{beamer}

\usetheme{metropolis}

\begin{document}

\begin{frame}{First}
  This frame looks fine
\end{frame}

\begin{frame}[standout]
  Questions?
\end{frame}

\begin{frame}{Another Slide}
  This frame should not be dark
\end{frame}
  
\end{document}

```

**Comment by alex-ball** [comment]
You will have seen from the manual that beamerswitch runs beamer with the `ignorenonframetext` option, and if you try your example with `\documentclass[ignorenonframetext]{beamer}`, you'll see that that is what causes the problem.

As per the Quick start guide (section 1 of the manual), you can fix this for your MWE by adding a mode line:

```latex
\begin{document}
\mode<all>
```

However, you only get the full benefit of beamerswitch (specifically the class-switching to article mode) if you can run with the `ignorenonframetext` option active. The problem is that metropolis closes the group that changes the style to standout *after* the mode is reset in `\beamer@reseteecodes`. At the time of writing, beamer has this:

```latex
\def\beamer@reseteecodes{\gdef\beamer@entrycode{}\gdef\beamer@exitcode{}%
  \beamer@slideinframe=1\relax\beamer@resumemode}
```

Metropolis has this:

```latex
\apptocmd{\beamer@reseteecodes}{%
  \ifbool{metropolis@standout}{
    \endgroup
    \boolfalse{metropolis@standout}
  }{}
}{}{}
```

What it should do is insert this code before `\beamer@resumemode` using `\patchcmd` instead of `\apptocmd`.

You can put it in the correct place yourself by doing the following:

```latex
\usetheme{metropolis}
\makeatletter
\def\beamer@reseteecodes{\gdef\beamer@entrycode{}\gdef\beamer@exitcode{}%
  \beamer@slideinframe=1\relax\ifbool{metropolis@standout}{\endgroup
    \boolfalse{metropolis@standout}}{}\beamer@resumemode}
\makeatother
```

whereupon you will no longer need the `\mode<all>` line.

Note that if anything else fiddles with `\beamer@reseteecodes` you may need to ensure it is loaded after these lines, or incorporate the changes into the above code, depending on how it does it.

**Comment by alex-ball** [comment]
Upstream issue has been reported under matze/mtheme#236 and matze/mtheme#335.

Fix introduced in matze/mtheme@1eef71d7.

**Comment by jlconlin** [comment]
So the fix you refer to has been available for several years, but there is still a problem. Does the fix not fix the issue?

**Comment by alex-ball** [comment]
There is "available" and "available". The fix was added to the master branch on GitHub in August 2018, but the current **release** is version 1.2 from January 2017. If you want the fixed code you'll have to take it from GitHub rather than rely on your distribution's packages, but I've no idea if the current, unreleased commit is in a production-ready state.
